[options]
addons_path = /opt/odoo-src/odoo/addons,/opt/odoo-src/odoo/odoo/addons,/opt/odoo-src/enterprise,/opt/odoo-src/design-themes,/mnt/extra-addons
upgrade_path = /mnt/upgrade/upgrade-util/src,/mnt/upgrade/upgrade/migrations
db_host = db
db_user = odoo
db_password = odoo
