[options]
addons_path = /mnt/reference/odoo/addons,/mnt/reference/odoo/odoo/addons,/mnt/reference/enterprise,/mnt/reference/design-themes,/mnt/extra-addons
upgrade_path = /mnt/upgrade/upgrade-util/src
db_host = db
db_user = odoo
db_password = odoo
data_dir = /var/lib/odoo
